FROM python:3.9

RUN cd /usr/src && \
    rm -rf app && \
    git clone https://github.com/TurkuNLP/Turku-neural-parser-pipeline.git app

WORKDIR /usr/src/app

RUN pip3 install --upgrade pip
RUN pip3 install --upgrade --no-cache-dir -r requirements.txt && \
	pip3 install torch==1.9.1+cu111 -f https://download.pytorch.org/whl/torch_stable.html

ENV PYTHONPATH /usr/src/app/

RUN python3 fetch_models.py fi_tdt_dia
