from snakemake.utils import Paramspace
import pandas
from os.path import join as pjoin
from os import chdir


DOWNLOADS = "downloads"
WORK = "work"


OPENSUBTITLES_URL = "https://opus.nlpl.eu/download.php?f=OpenSubtitles/v2018/parsed/fi.zip"


rule download_opensubtitles:
    output:
        pjoin(DOWNLOADS, "opensubs18.fi.zip)
    shell:
        "mkdir -p $(dirname {output}) && " +
        " wget " +
        " {params.url}" +
        " -O {output}"


rule run_tnpp:
    input:
        pjoin(DOWNLOADS, "fi_part_1.txt.gz")
    output:
        pjoin(WORK, "oscar.conllu")
    singularity:
        "docker://ghcr.io/frankier/blur_slurm_dispersion_tnpp@sha256:bf7a2a7e4fdfe1c94578fa6a5480d584f3e16bdf02c1eeb5f8bf9780bfba734c"
    shell:
        "mkdir -p $(dirname {output}) && " +
        " PYTHONPATH=/usr/src/app/:${{PYTHONPATH:-}} " +
        " gzcat {input} | head 50000 | python -m full_pipeline_stream " +
        " > {output}"


rule get_divergences_opensubs18_fi:
    input:
        pjoin(WORK, "opensubs18.fi.zip)
    output:
        pjoin(WORK, "opensubs18.fi.parquet")
    shell:
        "mk_disp --lemma" +
        " --corpus-type opensubs18 " +
        " {output}" +
        " {input}"


rule get_divergences_oscar_fi:
    input:
        pjoin(WORK, "oscar.fi.conllu")
    output:
        pjoin(WORK, "oscar.fi.parquet")
    run:
        "mk_disp --lemma" +
        " --corpus-type conllu " +
        " {output}" +
        " {input}"
