from snakemake.utils import Paramspace
import pandas
from os.path import join as pjoin
from os import chdir


DOWNLOADS = "downloads"
WORK = "work"


OPENSUBTITLES_URL = "https://opus.nlpl.eu/download.php?f=OpenSubtitles/v2018/parsed/fi.zip"


rule all:
    input:
        pjoin(WORK, "opensubs18.fi.parquet"),
        pjoin(WORK, "oscar.fi.parquet")


rule download_opensubtitles:
    output:
        pjoin(DOWNLOADS, "opensubs18.fi.zip")
    shell:
        "mkdir -p " + WORK + " && " +
        " wget " + OPENSUBTITLES_URL + " -O {output}"


rule run_tnpp:
    input:
        pjoin(DOWNLOADS, "fi_part_1.txt.gz")
    output:
        pjoin(WORK, "oscar.fi.conllu")
    singularity:
        "docker://ghcr.io/frankier/blur_slurm_dispersion_tnpp@sha256:bf7a2a7e4fdfe1c94578fa6a5480d584f3e16bdf02c1eeb5f8bf9780bfba734c"
    shell:
        "mkdir -p " + WORK + " && " +
        " zcat {input} | head -100 " +
        " | CUDA_VISIBLE_DEVICES=0 "
        " python -m tnpp_parse " +
        " --conf-yaml /usr/src/app/models_fi_tdt_dia/pipelines.yaml " +
        " > {output} || test $? -eq 141" # Mask 141 = SIGPIPE exits


rule get_divergences_opensubs18_fi:
    input:
        pjoin(DOWNLOADS, "opensubs18.fi.zip")
    output:
        pjoin(WORK, "opensubs18.fi.parquet")
    shell:
        "mk_disp --lemma" +
        " --corpus-type opensubs18 " +
        " {output}" +
        " {input}"


rule get_divergences_oscar_fi:
    input:
        pjoin(WORK, "oscar.fi.conllu")
    output:
        pjoin(WORK, "oscar.fi.parquet")
    shell:
        "mk_disp --lemma " +
        " --corpus-type conllu " +
        " {output} " +
        " {input} "
