name: Docker

on:
  push:
  pull_request:

jobs:
  ray_param_search:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Build/push
        uses: whoan/docker-build-with-cache-action@v5
        with:
          registry: ghcr.io
          image_name: frankier/wordfreak
          dockerfile: ray_param_search/Dockerfile
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
